# Generated by Django 2.2 on 2020-04-10 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='alias',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
